### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by yramachers** [drbenmorgan/warwick-legend#1]
The branch called firstAttempt collects bits and pieces from the various examples to steer towards a first executable. However, while starting that, missing code files had to be named, ideally with a coding convention. I see that as an issue sinceI didn't simply want to dictate that.

Currently the include files for the skeleton main() start with "LG..." for Legend. Would be good to fix this issue before more code appears, needing re-naming potentially. The executable name firstAttempt.cc is already bad enough.

**Comment by drbenmorgan** [comment]
For now, let's keep it simple and along the lines of the Geant4 examples (as this essentially how this is going to be structured, so

1. Decide on a name for the actual executable (`warwick-legend`?)
2. Move `firstAttempt.cc` -> `warwick-legend.cc`
3. Headers/Classes named as `PREFIXClassName.h`, `class PREFIXClassName`. `LG`'s fine as the prefix given this is going to be standalone, but feel free to change this to something like `WLGD` or `WarwickLegend` if you prefer additional clarity. 

It's pretty trivial to change these easily later on using VScode via the [refactoring tools](https://code.visualstudio.com/docs/editor/refactoring), or [clang-tools](https://clang.llvm.org/docs/ClangTools.html) and [clang-tools-extra](http://clang.llvm.org/extra/)(some docs [here](https://clang.llvm.org/extra/index.html)). Those are available on SCRTP either through modules or in CVMFS from the `sft.cern.ch` repo (or on macOS from the homebrew install of the `llvm` formula). In other words, easy to change when and if required!

So I'd go ahead and merge things modulo the scheme outline above. We can then iterate as we go along. Once you've done that, I'll set up `.clang-tidy/format` files to automate those parts.
