### ISSUE TITLE
Scorer/SD design

### ISSUE THREAD

**Issue by yramachers** [drbenmorgan/warwick-legend#16]
The scorers I am thinkng of at the moment, see below, are easy to write but I am still not decided whether they will do the job. Maybe this needs some more discussion hence this issue.

I noted on paper so far for scoring in a simple ntuple:
- particle ID
- parent ID
- parent PDG code (have to check how to do that)
- interaction (collision) location 
- time of interaction
- track vertex (where created)

All the above can be obtained from the G4Track, i.e. easy access.

The above should then be filtered on particle definitions (a) neutron and (b) ion 77Ge (filters are predefined). I am thinking of 2 multi function detectors, (1) attached to the LAr volume and the ULar volume, (2) to the Ge volume (with the 77Ge filter). I am currently not interested in the water volume.

Question is, is it good enough to get hold of the track vertex? I can't see any easy way of getting hold of the entire history of a filtered hit of interest, here a Ge77 production. Maybe scoring the neutrons is superfluous (not for testing of output though). We are only interested in them in the context of neutrons producing Ge77 after all. I am already disregarding everything the muons do, except the production of a neutron, assuming that very neutron then does something to allow it store its parent ID and vertex location which leads back to the muon.

Another item to keep in mind is that one can filter (with code) the scorer action. At the moment I just insist on filtering on non-boundary step status, i.e. every collision step passes. One can filter a lot stronger, for instance there is a scorer (with filtering conditions) considering only production of secondary particles in general. I quite like the idea but am undecided yet whether it'll do what we need. It may. 

Just to say that none of the scorers for our purpose has to be constrained on collision steps only. The more I think about it, they probably shouldn't.

**Comment by drbenmorgan** [comment]
> Question is, is it good enough to get hold of the track vertex? I can't see any easy way of getting hold of the entire history of a filtered hit of interest, here a Ge77 production. Maybe scoring the neutrons is superfluous (not for testing of output though). We are only interested in them in the context of neutrons producing Ge77 after all. I am already disregarding everything the muons do, except the production of a neutron, assuming that very neutron then does something to allow it store its parent ID and vertex location which leads back to the muon.

I think at least for recording the history, we'd need to use a concrete class of [`G4VUserTrackInformation`](http://geant4-userdoc.web.cern.ch/geant4-userdoc/UsersGuides/ForApplicationDeveloper/html/UserActions/userInformationClasses.html). Searching through the examples [gives quite a few use cases](https://geant4.kek.jp/lxr/search?string=G4VUserTrackInformation) so can likely adapt those.

**Comment by yramachers** [comment]
Fair enough. I was hoping to use only primitive scorers but that seems to stretch the concept a little too far. 

The extended/runAndEvent/RE01 example looks promising.

This could lead to a primitive scorer which simply counts the number of Ge77 produced in Ge and a history of relevant particles and locations from the track information whenever required (always collected, rarely called upon). Since that happens rarely, for testing, one could simply switch the trigger particle from Ge77 to neutron for instance.

**Comment by yramachers** [comment]
Branch 'newScorer' has the example RE01 as origin and seems to work fine. Caution - currently simply prints trajectories to screen without(!) filterting, every little e- is there - very long output. All that information needs filtering and then output to disk, easiest with the existing root TTree output mechanism - accessible at the same point, i.e. EndOfEventAction function in WLGDEvent.

The 'simplerScorer' branch is a largely unsuccessful attempt at achieving the same effect using only primitive scorers with a multifunctiondetector. I don't think that works as intended hence the trajectory, track stacking mechanism from above. Conceptually, there is a big difference between 'hits' and 'tracks'. Difficult to get a whole history with hits while that can be done following tracks in an event. There still needs to be a sensitive detector to register hits, but for our purposes, that can now reduce to Germanium volume only and filter purely on Ge77 production. That should in the end also be the filter for dumping the entire track history. At the moment, all hits in the various logical volumes of interest are registered for mu-, neutron and Ge77 in the particle filter. Easy to change.

**Comment by yramachers** [comment]
I think with #28 we now got the filter and all we need as output, switchable for storing trajectories or not. For production runs, the only remaining change would be not to score hits from neutrons anymore but only from Ge77 production. 

I've seen Ge77 production taking place and being stored in a few test runs. The PDG number looks odd but makes sense hence is useful in case the history is being extracted in runs with trajectory storage. 

One item to look out for is the neutron time cut. If many Ge77 hits occur close to the time limit, it should be raised. Time scoring is implemented for hits.
