### ISSUE TITLE
GDML output - one-off

### ISSUE THREAD

**Issue by yramachers** [drbenmorgan/warwick-legend#24]
I am tempted to look into enabling GDML output of the geometry, more as a one-off to check the geometry with the ROOT gdml reader. Making a picture would also be useful for presentations. I'd like to convince myself that the geometries as coded are really what I think they are. Visualisation would also be good and do the job though. Not sure whether to go the route above. If it easy enough, I rekcon a branch version which only outputs the gdml file(s) would be useful.

**Comment by drbenmorgan** [comment]
It can't hurt to have the option to do this. I'll try and have a look this week.

**Comment by yramachers** [comment]
Done.
